config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "/home/about" => "homes#about"
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!,except: [:top, :about]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
    user_path(current_user)
    end
    
    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :identification, only: [:edit]
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book), notice: "You have created book successfully."
    else
       @user = current_user
       @books = Book.all
       render:index
    end
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book), notice: "You have updated user successfully."
    else
       render:edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  
  private
  
    def identification
    book = Book.find(params[:id])
      if book.user_id != current_user.id
        redirect_to books_path
      end
    end
  
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
    
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :identification, only: [:edit]
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
       render:edit
    end
  end
  
  private
    def identification
    user = User.find(params[:id])
      if user != current_user
        redirect_to user_path(current_user)
      end
    end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= @book.errors.count %>error prohibited this book from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
            <%= f.text_field :title , class: 'form-control book_title' %>
          </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
            <%= f.text_area :body , class: 'form-control book_body' %>
          </div>
        <div class="form-group">
            <%= f.submit "Update Book", class: 'btn btn-success' %>
        </div>
        <% end %>
        <%= link_to "Show",book_path(@book) %>
        |
        <%= link_to "Back",books_path %>
     </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>error prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user ,book: @book %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title , class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body , class: 'form-control book_body' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book' , class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
           </td>
           <td>
              <%= book.body %>
           </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user ,book: @book %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @booknew, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title , class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body , class: 'form-control book_body' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book' , class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <br>
              <%= link_to @user.name, user_path(@user) %>
            </td>
            <td><%= @book.title %>
            <td><%= @book.body %></td>
            <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
    welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<title>Bookers2Ver2</title>
<body>
 <main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
       <h1>welcome to
       <i class="fas fa-book"></i>
       <strong>Bookers</strong> !!
       </h1>
       <p>In
       <i class="fas fa-book"></i>
       <strong>Bookers</strong>,</p>
       <p>you can share and exchange your opinions , inpressions , and emotions</p>
       <p>about various books!</p>
       <div class="btn-wrapper col-10 mx-auto">
         <div class="row">
           <%= link_to "Log in",new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
         </div>
         <div class="row">
           <%= link_to "Sign up",new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
         </div>
       </div>
      </div>
    </div>
  </div>
</main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand p-3" href="/">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Home', user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            
            
            <% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <p id="notice"><% if flash[:notice] %>
    <%= flash[:notice] %>
    <% end %>
    <%= yield %></p>
  </main>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to "", edit_user_path(user), class: 'fas fa-user-cog btn btn-outline-secondary btn-block' %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>User info</h1>
        <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= @user.errors.count %>error prohibited this book from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name , class: 'form-control name' %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" , class: 'form-control-file user_image' %>
        </div>
        <div class="form-group">
          <label for="user_introducion">Introduction</label>
          <%= f.text_area :introduction , class: 'form-control introduction' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: 'btn btn-success' %>
        </div>
        <% end %>
     </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user ,book: @book %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title , class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body , class: 'form-control book_body' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book' , class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
            </td>
            <td>
              <%= user.name %>
            </td>
           <td>
              <%= link_to "Show",user_path(user.id) %>
           </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user ,book: @book %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title , class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body , class: 'form-control book_body' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book' , class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
           </td>
           <td>
              <%= book.body %>
           </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>